package org.lababidy.database;
// Generated Jun 27, 2014 9:57:54 PM by Hibernate Tools 3.6.0

import javax.xml.bind.annotation.XmlRootElement;



/**
 * Visitor generated by hbm2java
 */
@XmlRootElement
public class Visitor implements java.io.Serializable {


     private int vid;

    private int vcid;
    private String vfname;
    private String vlname;
    private String vmobile;
    private String vtelephone;
    private String vemail;

    private String vnotes;

   	
    
   
    public int getVid() {
        return this.vid;
    }
    
    public void setVid(int vid) {
        this.vid = vid;
    }
    public int getVcid() {
        return vcid;
    }

    public void setVcid(int vcid) {
        this.vcid = vcid;
    }

    public String getVFname() {
        return vfname;
    }
    
    public void setVFname(String vfname) {
        this.vfname = vfname;
    }
    public String getVLname() {
        return vlname;
    }
    
    public void setVLname(String vlname) {
        this.vlname = vlname;
    }
    public String getVMobile() {
        return this.vmobile;
    }
    
    public void setVMobile(String vmobile) {
        this.vmobile = vmobile;
    }
    public String getVTelephone() {
        return this.vtelephone;
    }
    
    public void setVTelephone(String vtelephone) {
        this.vtelephone = vtelephone;
    }
    public String getVEmail() {
        return this.vemail;
    }
    
    public void setVEmail(String vemail) {
        this.vemail = vemail;
    }
    public String getNnotes() {
        return this.vnotes;
    }

    public void setvNotes(String vnotes) {
        this.vnotes = vnotes;
    }
    @Override
    public String toString() {
        return vfname + " " + vlname;
    }

    public String nametoString() {
        return vid + "|" + vcid + "|" + vfname + "|" + vlname + "|" + vtelephone + "|" + vemail + "|" + vnotes;
    }

}



